### ISSUE TITLE
Single quotes are not escaped

### ISSUE THREAD

**Issue by idleberg** [avakar/pycson#7]
When converting JSON to CSON, single quotes are not escaped

**Example**:

``` json
{
  "description": "It's me, Mario!"
}
```

gets converted to

``` cson
description: 'It's me, Mario!'
```

when it should be

``` cson
description: 'It\'s me, Mario!'
```

The single quote is unescaped properly when converting CSON to JSON.

**Comment by avakar** [comment]
Hi, thank's for the issue! The problem should now be solved in 0.7.
